// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = MainHeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *MainHero → Default → Primary*
 */
export interface MainHeroSliceDefaultPrimary {
  /**
   * Heading field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Timestamp field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.timestamp
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  timestamp: prismic.DateField;

  /**
   * Content1 field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.content1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content1: prismic.RichTextField;

  /**
   * Image field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content2 field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.content2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content2: prismic.RichTextField;

  /**
   * video1 field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.video1
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video1: prismic.EmbedField;

  /**
   * Content3 field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.content3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content3: prismic.RichTextField;

  /**
   * video2 field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.video2
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video2: prismic.EmbedField;

  /**
   * Content4 field in *MainHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_hero.default.primary.content4
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content4: prismic.RichTextField;
}

/**
 * Default variation for MainHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainHero*
 */
type MainHeroSliceVariation = MainHeroSliceDefault;

/**
 * MainHero Shared Slice
 *
 * - **API ID**: `main_hero`
 * - **Description**: MainHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainHeroSlice = prismic.SharedSlice<
  "main_hero",
  MainHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      MainHeroSlice,
      MainHeroSliceDefaultPrimary,
      MainHeroSliceVariation,
      MainHeroSliceDefault,
    };
  }
}
